create table if not exists public.system_health_checks (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  status text not null check (status in ('ok','warn','critical')),
  issues jsonb not null default '[]'::jsonb check (jsonb_typeof(issues)='array'),
  metrics jsonb not null default '{}'::jsonb check (jsonb_typeof(metrics)='object'),
  source text not null default 'cron' check (source in ('cron','manual','migration'))
);

create index if not exists system_health_checks_checked_at_idx
  on public.system_health_checks (checked_at desc);

alter table public.system_health_checks enable row level security;

drop policy if exists system_health_checks_admin_select on public.system_health_checks;
create policy system_health_checks_admin_select
  on public.system_health_checks
  for select
  to authenticated
  using (private.is_admin());

revoke all on table public.system_health_checks from public, anon, authenticated;
grant select on table public.system_health_checks to authenticated;

create or replace function private.run_uti_health_check(p_source text default 'cron')
returns bigint
language plpgsql
security definer
set search_path='public','private','cron','pg_temp'
as $$
declare
  v_now timestamptz := now();
  v_active_admissions integer := 0;
  v_active_admins integer := 0;
  v_duplicate_active_beds integer := 0;
  v_duplicate_charge_cycles integer := 0;
  v_missing_rates integer := 0;
  v_state_mismatches integer := 0;
  v_mfa_required boolean := false;
  v_billing_job_active boolean := false;
  v_last_billing_success timestamptz;
  v_recent_billing_failures integer := 0;
  v_issues jsonb := '[]'::jsonb;
  v_metrics jsonb;
  v_status text := 'ok';
  v_id bigint;
begin
  if p_source not in ('cron','manual','migration') then
    raise exception 'Fonte de health check inválida.';
  end if;

  select count(*) into v_active_admissions
  from public.admissions
  where status in ('active','discharge_pending');

  select count(*) into v_active_admins
  from public.profiles
  where active=true and role='admin';

  select count(*) into v_duplicate_active_beds
  from (
    select bed
    from public.admissions
    where status='active'
    group by bed
    having count(*) > 1
  ) x;

  select count(*) into v_duplicate_charge_cycles
  from (
    select admission_id, cycle_key
    from public.charges
    where cycle_key is not null and cancelled_at is null
    group by admission_id, cycle_key
    having count(*) > 1
  ) x;

  select count(*) into v_missing_rates
  from public.admissions a
  where a.status in ('active','discharge_pending')
    and not exists (
      select 1
      from public.rate_periods r
      where r.admission_id=a.id
        and r.effective_at <= v_now
    );

  select count(*) into v_state_mismatches
  from public.admissions a
  where (a.status='active' and a.discharge_at is not null)
     or (a.status='finalized' and a.discharge_at is null);

  select coalesce(s.mfa_required,false) into v_mfa_required
  from public.app_settings s
  where s.id=1;

  select coalesce(bool_or(j.active),false) into v_billing_job_active
  from cron.job j
  where j.jobname='imec-uti-sync-daily-charges';

  select max(d.end_time) into v_last_billing_success
  from cron.job j
  join cron.job_run_details d on d.jobid=j.jobid
  where j.jobname='imec-uti-sync-daily-charges'
    and d.status='succeeded';

  select count(*) into v_recent_billing_failures
  from cron.job j
  join cron.job_run_details d on d.jobid=j.jobid
  where j.jobname='imec-uti-sync-daily-charges'
    and d.start_time >= v_now - interval '6 hours'
    and d.status <> 'succeeded';

  if v_active_admins < 1 then
    v_issues := v_issues || jsonb_build_array(jsonb_build_object(
      'code','NO_ACTIVE_ADMIN','severity','critical',
      'message','Nenhum administrador ativo está disponível.'
    ));
  end if;

  if not v_mfa_required then
    v_issues := v_issues || jsonb_build_array(jsonb_build_object(
      'code','MFA_ENFORCEMENT_OFF','severity','critical',
      'message','A exigência server-side de MFA está desativada.'
    ));
  end if;

  if v_duplicate_active_beds > 0 then
    v_issues := v_issues || jsonb_build_array(jsonb_build_object(
      'code','DUPLICATE_ACTIVE_BED','severity','critical',
      'message','Há mais de uma internação ativa no mesmo leito.',
      'count',v_duplicate_active_beds
    ));
  end if;

  if v_duplicate_charge_cycles > 0 then
    v_issues := v_issues || jsonb_build_array(jsonb_build_object(
      'code','DUPLICATE_BILLING_CYCLE','severity','critical',
      'message','Foram detectados ciclos de cobrança duplicados.',
      'count',v_duplicate_charge_cycles
    ));
  end if;

  if v_missing_rates > 0 then
    v_issues := v_issues || jsonb_build_array(jsonb_build_object(
      'code','MISSING_RATE','severity','critical',
      'message','Há internações abertas sem condição de diária válida.',
      'count',v_missing_rates
    ));
  end if;

  if v_state_mismatches > 0 then
    v_issues := v_issues || jsonb_build_array(jsonb_build_object(
      'code','ADMISSION_STATE_MISMATCH','severity','warn',
      'message','Há internações com status e data de alta inconsistentes.',
      'count',v_state_mismatches
    ));
  end if;

  if not v_billing_job_active then
    v_issues := v_issues || jsonb_build_array(jsonb_build_object(
      'code','BILLING_CRON_INACTIVE','severity','critical',
      'message','O job automático de diárias está ausente ou inativo.'
    ));
  end if;

  if v_last_billing_success is null or v_last_billing_success < v_now - interval '2 hours' then
    v_issues := v_issues || jsonb_build_array(jsonb_build_object(
      'code','BILLING_CRON_STALE',
      'severity',case when v_active_admissions > 0 then 'critical' else 'warn' end,
      'message','O faturamento automático não registra execução bem-sucedida recente.'
    ));
  end if;

  if v_recent_billing_failures > 0 then
    v_issues := v_issues || jsonb_build_array(jsonb_build_object(
      'code','BILLING_CRON_FAILURES','severity','warn',
      'message','Houve falha recente no job automático de diárias.',
      'count',v_recent_billing_failures
    ));
  end if;

  if exists (
    select 1 from jsonb_array_elements(v_issues) e
    where e->>'severity'='critical'
  ) then
    v_status := 'critical';
  elsif jsonb_array_length(v_issues) > 0 then
    v_status := 'warn';
  end if;

  v_metrics := jsonb_build_object(
    'active_admissions', v_active_admissions,
    'active_admins', v_active_admins,
    'duplicate_active_beds', v_duplicate_active_beds,
    'duplicate_charge_cycles', v_duplicate_charge_cycles,
    'missing_rates', v_missing_rates,
    'state_mismatches', v_state_mismatches,
    'mfa_required', v_mfa_required,
    'billing_job_active', v_billing_job_active,
    'billing_last_success', v_last_billing_success,
    'billing_recent_failures', v_recent_billing_failures
  );

  insert into public.system_health_checks(status,issues,metrics,source)
  values(v_status,v_issues,v_metrics,p_source)
  returning id into v_id;

  delete from public.system_health_checks
  where checked_at < v_now - interval '90 days';

  return v_id;
end;
$$;

revoke all on function private.run_uti_health_check(text) from public, anon, authenticated;

select cron.schedule(
  'imec-uti-health-check',
  '*/15 * * * *',
  'select private.run_uti_health_check();'
);

select private.run_uti_health_check('migration');
