create table if not exists public.system_alerts (
  id bigint generated by default as identity primary key,
  alert_key text not null,
  code text not null,
  severity text not null check (severity in ('warn','critical')),
  message text not null,
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details)='object'),
  status text not null default 'open' check (status in ('open','acknowledged','resolved')),
  first_detected_at timestamptz not null default now(),
  last_detected_at timestamptz not null default now(),
  occurrence_count integer not null default 1 check (occurrence_count >= 1),
  health_check_id bigint references public.system_health_checks(id) on delete set null,
  acknowledged_at timestamptz,
  acknowledged_by uuid references public.profiles(id) on delete set null,
  acknowledged_by_name text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  check (
    (status='open' and acknowledged_at is null)
    or (status='acknowledged' and acknowledged_at is not null)
    or status='resolved'
  )
);

create unique index if not exists system_alerts_unresolved_key_uidx
  on public.system_alerts(alert_key)
  where status in ('open','acknowledged');

create index if not exists system_alerts_status_severity_idx
  on public.system_alerts(status,severity,last_detected_at desc);

create index if not exists system_alerts_last_detected_idx
  on public.system_alerts(last_detected_at desc);

alter table public.system_alerts enable row level security;

drop policy if exists system_alerts_admin_select on public.system_alerts;
create policy system_alerts_admin_select
  on public.system_alerts
  for select
  to authenticated
  using (private.is_admin());

revoke all on table public.system_alerts from public, anon, authenticated;
grant select on table public.system_alerts to authenticated;

create or replace function private.upsert_uti_system_alert(
  p_alert_key text,
  p_code text,
  p_severity text,
  p_message text,
  p_details jsonb default '{}'::jsonb,
  p_detected_at timestamptz default now(),
  p_health_check_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path='public','private','pg_temp'
as $$
declare
  v_id bigint;
  v_old_severity text;
  v_old_status text;
  v_escalated boolean := false;
begin
  if nullif(trim(coalesce(p_alert_key,'')),'') is null then
    raise exception 'Chave do alerta ausente.';
  end if;
  if nullif(trim(coalesce(p_code,'')),'') is null then
    raise exception 'Código do alerta ausente.';
  end if;
  if p_severity not in ('warn','critical') then
    raise exception 'Severidade de alerta inválida.';
  end if;
  if nullif(trim(coalesce(p_message,'')),'') is null then
    raise exception 'Mensagem do alerta ausente.';
  end if;

  select id,severity,status
    into v_id,v_old_severity,v_old_status
  from public.system_alerts
  where alert_key=p_alert_key
    and status in ('open','acknowledged')
  for update;

  if found then
    v_escalated := v_old_severity='warn' and p_severity='critical';

    update public.system_alerts
    set severity=p_severity,
        message=trim(p_message),
        details=coalesce(p_details,'{}'::jsonb),
        last_detected_at=coalesce(p_detected_at,now()),
        occurrence_count=occurrence_count+1,
        health_check_id=p_health_check_id,
        status=case when v_escalated then 'open' else status end,
        acknowledged_at=case when v_escalated then null else acknowledged_at end,
        acknowledged_by=case when v_escalated then null else acknowledged_by end,
        acknowledged_by_name=case when v_escalated then null else acknowledged_by_name end,
        resolved_at=null
    where id=v_id;

    if v_escalated then
      insert into public.audits(user_name,user_id,action,detail)
      values(
        'Sistema',null,'Alerta operacional escalado',
        p_code||' • CRÍTICO • '||trim(p_message)
      );
    end if;

    return v_id;
  end if;

  insert into public.system_alerts(
    alert_key,code,severity,message,details,status,
    first_detected_at,last_detected_at,occurrence_count,health_check_id
  )
  values(
    trim(p_alert_key),trim(p_code),p_severity,trim(p_message),
    coalesce(p_details,'{}'::jsonb),'open',
    coalesce(p_detected_at,now()),coalesce(p_detected_at,now()),1,p_health_check_id
  )
  returning id into v_id;

  insert into public.audits(user_name,user_id,action,detail)
  values(
    'Sistema',null,'Alerta operacional aberto',
    p_code||' • '||upper(p_severity)||' • '||trim(p_message)
  );

  return v_id;
end;
$$;

create or replace function private.resolve_uti_system_alert(
  p_alert_key text,
  p_resolved_at timestamptz default now()
)
returns boolean
language plpgsql
security definer
set search_path='public','private','pg_temp'
as $$
declare
  v_code text;
  v_message text;
begin
  update public.system_alerts
  set status='resolved',
      resolved_at=coalesce(p_resolved_at,now())
  where alert_key=p_alert_key
    and status in ('open','acknowledged')
  returning code,message into v_code,v_message;

  if not found then return false; end if;

  insert into public.audits(user_name,user_id,action,detail)
  values('Sistema',null,'Alerta operacional resolvido',v_code||' • '||v_message);

  return true;
end;
$$;

create or replace function private.reconcile_uti_health_snapshot(p_health_check_id bigint)
returns void
language plpgsql
security definer
set search_path='public','private','pg_temp'
as $$
declare
  h public.system_health_checks;
  i jsonb;
  v_code text;
  a record;
begin
  select * into h
  from public.system_health_checks
  where id=p_health_check_id;

  if not found then
    raise exception 'Health check não encontrado.';
  end if;

  for i in select value from jsonb_array_elements(coalesce(h.issues,'[]'::jsonb))
  loop
    v_code:=nullif(trim(i->>'code'),'');
    if v_code is null then continue; end if;

    perform private.upsert_uti_system_alert(
      'health:'||v_code,
      v_code,
      case when i->>'severity'='critical' then 'critical' else 'warn' end,
      coalesce(nullif(trim(i->>'message'),''),'Alerta operacional detectado.'),
      i,
      h.checked_at,
      h.id
    );
  end loop;

  for a in
    select alert_key
    from public.system_alerts
    where alert_key like 'health:%'
      and status in ('open','acknowledged')
      and not exists (
        select 1
        from jsonb_array_elements(coalesce(h.issues,'[]'::jsonb)) j
        where 'health:'||coalesce(j->>'code','') = public.system_alerts.alert_key
      )
  loop
    perform private.resolve_uti_system_alert(a.alert_key,h.checked_at);
  end loop;
end;
$$;

create or replace function private.system_health_alert_trigger()
returns trigger
language plpgsql
security definer
set search_path='public','private','pg_temp'
as $$
begin
  perform private.reconcile_uti_health_snapshot(new.id);
  return new;
end;
$$;

drop trigger if exists system_health_alert_reconcile on public.system_health_checks;
create trigger system_health_alert_reconcile
after insert on public.system_health_checks
for each row execute function private.system_health_alert_trigger();

create or replace function private.run_uti_observability_watchdog()
returns integer
language plpgsql
security definer
set search_path='public','private','cron','pg_temp'
as $$
declare
  v_now timestamptz:=now();
  v_last_health timestamptz;
  v_health_job_active boolean:=false;
  v_health_failures integer:=0;
  v_active_admissions integer:=0;
  v_touched integer:=0;
  v_severity text;
begin
  select max(checked_at) into v_last_health
  from public.system_health_checks;

  select coalesce(bool_or(active),false) into v_health_job_active
  from cron.job
  where jobname='imec-uti-health-check';

  select count(*) into v_health_failures
  from cron.job j
  join cron.job_run_details d on d.jobid=j.jobid
  where j.jobname='imec-uti-health-check'
    and d.start_time >= v_now-interval '1 hour'
    and d.status not in ('succeeded','running');

  select count(*) into v_active_admissions
  from public.admissions
  where status in ('active','discharge_pending');

  if not v_health_job_active
     or v_last_health is null
     or v_last_health < v_now-interval '35 minutes' then
    v_severity:=case when v_active_admissions>0 then 'critical' else 'warn' end;
    perform private.upsert_uti_system_alert(
      'watchdog:health-monitor',
      'HEALTH_MONITOR_STALE',
      v_severity,
      case
        when not v_health_job_active then 'O job do monitor de saúde está inativo ou ausente.'
        else 'O monitor de saúde não registra uma execução recente.'
      end,
      jsonb_build_object(
        'last_health_check',v_last_health,
        'health_job_active',v_health_job_active,
        'active_admissions',v_active_admissions
      ),
      v_now,
      null
    );
    v_touched:=v_touched+1;
  else
    if private.resolve_uti_system_alert('watchdog:health-monitor',v_now) then
      v_touched:=v_touched+1;
    end if;
  end if;

  if v_health_failures>0 then
    perform private.upsert_uti_system_alert(
      'watchdog:health-cron-failures',
      'HEALTH_CRON_FAILURES',
      'warn',
      'O monitor de saúde apresentou falha recente de execução.',
      jsonb_build_object('failures_last_hour',v_health_failures),
      v_now,
      null
    );
    v_touched:=v_touched+1;
  else
    if private.resolve_uti_system_alert('watchdog:health-cron-failures',v_now) then
      v_touched:=v_touched+1;
    end if;
  end if;

  delete from public.system_alerts
  where status='resolved'
    and resolved_at < v_now-interval '180 days';

  return v_touched;
end;
$$;

create or replace function private.acknowledge_uti_alert_impl(p_alert_id bigint)
returns text
language plpgsql
security definer
set search_path='public','private','pg_temp'
as $$
declare
  v_user text;
  a public.system_alerts;
begin
  if not private.is_admin() then
    raise exception 'Somente administradores podem reconhecer alertas.';
  end if;

  select * into a
  from public.system_alerts
  where id=p_alert_id
  for update;

  if not found then raise exception 'Alerta não encontrado.'; end if;
  if a.status='resolved' then return 'resolved'; end if;
  if a.status='acknowledged' then return 'acknowledged'; end if;

  v_user:=private.current_display_name();

  update public.system_alerts
  set status='acknowledged',
      acknowledged_at=now(),
      acknowledged_by=auth.uid(),
      acknowledged_by_name=v_user
  where id=p_alert_id;

  insert into public.audits(user_name,user_id,action,detail)
  values(
    v_user,auth.uid(),'Alerta operacional reconhecido',
    a.code||' • '||a.message
  );

  return 'acknowledged';
end;
$$;

create or replace function public.acknowledge_uti_alert(p_alert_id bigint)
returns text
language sql
set search_path='public','private','pg_temp'
as $$
  select private.acknowledge_uti_alert_impl(p_alert_id)
$$;

revoke all on function private.upsert_uti_system_alert(text,text,text,text,jsonb,timestamptz,bigint) from public, anon, authenticated;
revoke all on function private.resolve_uti_system_alert(text,timestamptz) from public, anon, authenticated;
revoke all on function private.reconcile_uti_health_snapshot(bigint) from public, anon, authenticated;
revoke all on function private.system_health_alert_trigger() from public, anon, authenticated;
revoke all on function private.run_uti_observability_watchdog() from public, anon, authenticated;
revoke all on function private.acknowledge_uti_alert_impl(bigint) from public, anon, authenticated;

revoke all on function public.acknowledge_uti_alert(bigint) from public, anon;
grant execute on function public.acknowledge_uti_alert(bigint) to authenticated;

select cron.schedule(
  'imec-uti-observability-watchdog',
  '7,22,37,52 * * * *',
  'select private.run_uti_observability_watchdog();'
);

select private.reconcile_uti_health_snapshot((select max(id) from public.system_health_checks));
select private.run_uti_observability_watchdog();
